live_config_reload = true

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 15
y = 10

[font]
builtin_box_drawing = false
size                = 12

[font.bold]
family = "GoMono Nerd Font Mono"

[font.bold_italic]
family = "GoMono Nerd Font Mono"


[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "GoMono Nerd Font Mono"


[font.normal]
family = "GoMono Nerd Font Mono"
style  = "Regular"


[font.offset]
x = 1
y = 2